users/urls.py
from django.urls import path, include
from . import views
from django.conf import settings  
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import url_reset

# Set the application namespace
app_name = 'users'

# Define URL patterns
urlpatterns = [
    # User registration
    path('register/', views.register, name='register'),
    
    # User login
    path('login/', views.login, name='login'),
    
    # User logout
    path('logout/', views.logout_view, name='logout'),
    
    # User profile
    path('profile/<int:pk>/', views.profile, name='profile'),
    
    # Edit user account
    path('edit_account/', views.edit_account, name='edit_account'),
    
    # Delete user account
    path('delete_account/', views.delete_account, name='delete_account'),
    
    # Password reset
    path('password-reset/', include('users.url_reset')),
]   

weather_you_do/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import handler403, handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
    path('users/', include ('users.urls')),
]

handler403 = handler403
handler404 = handler404
handler500 = handler500

users/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

# Model for user profiles
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # One-to-one relationship with User model
    name = models.CharField(max_length=200, blank=True, null=True)  # Name of the user
    username = models.CharField(max_length=80, blank=True, null=True)  # Username of the user
    email = models.EmailField(max_length=500, blank=True, null=True)  # Email of the user
    image = CloudinaryField('image', default='placeholder')  # Profile image stored on Cloudinary

    # String representation of the Profile model
    def __str__(self):
        return f'{self.user.username} Profile'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.forms import ModelForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

# Retrieve the custom User model
User = get_user_model()

# Form for user registration
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    # Initialize form with crispy form helper
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit', 'Sign Up'))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

# Form for profile editing
class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'username', 'email', 'image']

    # Initialize form with crispy form helper
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        # Sets form control class for styling
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control w-100'})

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm, ProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from .models import Profile
from django.views.decorators.csrf import csrf_protect

def register(request):
    """View for user registration."""
    if request.user.is_authenticated:
        return redirect('users:profile', pk=request.user.profile.id) 
    if request.method == 'POST':
        form = UserRegisterForm(request.POST) 
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.success(request, f'The account {user.username} was created successfully, now you can login.')
            return redirect('users:edit_account')
        else:
            messages.error(request, 'Ooops something went wrong!')
    else:
        form = UserRegisterForm() 
    return render(request, 'register.html', {'form': form})

@csrf_protect
def login(request):
    """View for user login."""
    if request.user.is_authenticated:
        return redirect('weather:index') 

    if request.method == 'POST':
        form = AuthenticationForm(request.POST)
        username = request.POST['username'].lower()
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except Exception:
            messages.error(request, 'Username does not exist!')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect('weather:index')
        else:
            messages.error(request, 'Username OR Password is incorrect!')
    else:
        form = AuthenticationForm()

    return render(request, 'login.html', {'form': form})

@login_required(login_url='users:login')
def edit_account(request):
    """View for editing user account."""
    profile = request.user.profile
    form = ProfileForm(instance=profile)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile Updated!')
            return redirect('users:profile', pk=profile.id)
    context = {
        'form': form
    }
    return render(request, 'profile_form.html', context)

@login_required(login_url='users:login')
def delete_account(request):
    """View for deleting user account."""
    profile = request.user.profile
    if request.method == 'POST':
        profile.delete()
        messages.success(request, 'Account Deleted!')
        return redirect('weather:index')
    return render(request, 'delete_account.html')

@login_required 
def profile(request, pk):
    """View for user profile."""
    profile = Profile.objects.get(id=pk)
    context = {
        'profile': profile
    }
    return render(request, 'profile.html', context)

@login_required 
def logout_view(request):
    """View for user logout."""
    if request.method == 'POST':
        logout(request)
        messages.success(request, 'User was successfully signed out!')
        return redirect('users:login')
    else:
        return render(request, 'logout.html')

users/templates/delete_account.html
{% extends 'weather/base.html' %}
{% load static %}

{% block content %}
<!-- Form to delete user account -->
<main class="container">
    <div class="row justify-content-center g-0">
        <div class="col-11 col-md-6 col-xl-4 p-2 mb-5 border border-dark border-2 rounded-4 justify-content-center">
            <form method="POST">
                {% csrf_token %}
                <p>Are you sure you want to delete your Account??</p>
                <!-- Link to go back to user profile -->
                <a class="login-register btn btn-primary" href="{% url 'users:profile' request.user.profile.id %}">
                    Back
                </a>
                <!-- Button to confirm account deletion -->
                <button type="submit" class="btn btn-primary">Confirm</button>
            </form>
        </div>
    </div>
</main>
{% endblock content %}

users/templates/login.html
{% extends "weather/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="content-section text-white"> <!-- Add text-white class to make text white -->
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Login</legend>
                        {{ form|crispy }} <!-- Render form using crispy forms -->
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-dark-blue" type="submit">Login</button>
                    </div>
                </form>
                <!-- Link to reset password -->
                <p class="mt-2 text-black">Forgot Password?:  <a href="{% url 'users:password_reset' %}" class="text-white">Password Reset</a></p>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Need An Account? <a class="ml-2 text-white" href="{% url 'users:register' %}">Register Now</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/logout.html
{% extends "weather/base.html" %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center">You have been logged out</h2>
            <div class="border-top pt-3 text-center">
                <small class="text-muted">
                    <!-- Link to sign in again -->
                    Login again <a href="{% url 'login' %}">Sign In</a>
                </small>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/password_reset.html
{% extends 'weather/base.html' %}

{% block content %}
<!-- Container for the password reset form -->
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <!-- Form for resetting the password -->
            <form method="post" class="accountform">
                <!-- Heading for the password reset section -->
                <h2 class="mb-4 text-white">Reset Password</h2> 
                <!-- Instructions for the user -->
                <p class="lead text-white">Please specify your email address to receive instructions for resetting it.</p> 
                <!-- Form field for entering the email address -->
                <div class="form-group">
                    <label for="id_email" class="required-field text-white">E-mail address:</label> 
                    {{ form.email }}
                    <!-- Display any form errors -->
                    <small class="form-text text-danger text-white">{{ form.email.errors }}</small>
                </div>
                <!-- Button to submit the form -->
                <button type="submit" class="btn btn-dark-blue mt-2">Reset Password</button>
                <!-- CSRF token for form submission -->
                <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/password_reset_complete.html
{% extends "weather/base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <!-- Inform the user that the password has been set -->
            <p class="mt-3 mt-md-3 text-white">Your password has been set. You may go ahead and log in now.</p>
            <!-- Button to redirect user to login page -->
            <p><a href="{% url 'users:login' %}" class="btn btn-dark-blue">Log in</a></p> 
        </div>
    </div>
</div>
{% endblock %}

users/templates/password_reset_confirm.html
{% extends "weather/base.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if validlink %}
                <!-- Heading for password reset -->
                <h2 class="mt-3 mb-4 text-white">Reset Password</h2>
                <!-- Inform the user about entering the new password -->
                <p class="text-white">Please enter your new password twice so we can verify you typed it in correctly.</p>
                <!-- Form to enter new password -->
                <form action="" method="post" class="accountform">
                    {% csrf_token %}
                    <div class="form-group mt-2">
                        <!-- Label for new password input -->
                        <label for="id_new_password1" class="text-white">New password:</label>
                        <!-- Input field for new password -->
                        {{ form.new_password1 }}
                        <!-- Display errors for new password -->
                        <small class="form-text text-danger">{{ form.new_password1.errors }}</small>
                    </div>
                    <div class="form-group mt-2">
                        <!-- Label for confirming new password input -->
                        <label for="id_new_password2" class="text-white">Confirm password:</label>
                        <!-- Input field for confirming new password -->
                        {{ form.new_password2 }}
                        <!-- Display errors for confirming new password -->
                        <small class="form-text text-danger">{{ form.new_password2.errors }}</small>
                    </div>
                    <!-- Button to change the password -->
                    <button type="submit" class="btn btn-dark-blue mt-3">Change my password</button>
                </form>
            {% else %}
                <!-- Inform the user about unsuccessful password reset -->
                <h2 class="text-white">Password reset unsuccessful</h2>
                <!-- Provide information about the reason for the unsuccessful reset -->
                <p class="text-white">The password reset link was invalid, possibly because it has already been used. Please request a new password reset.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

users/templates/password_reset_done.html
{% extends "weather/base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <!-- Inform the user about the email sent for setting the password -->
            <p class="mt-3 mt-md-3 text-center text-white">We've e-mailed you instructions for setting your password to the e-mail address you submitted.</p>
            <!-- Inform the user about the expected email arrival -->
            <p class="text-center text-white">You should be receiving it shortly.</p> 
        </div>
    </div>
</div>
{% endblock %}

users/templates/password_reset_email.html
{% autoescape off %}
<!-- Inform the user about the reason for receiving the email -->
You're receiving this e-mail because you requested a password reset for your user account at {{ site_name }}.

<!-- Provide the link for resetting the password -->
Please go to the following page and choose a new password:
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

<!-- Display the username in case the user has forgotten -->
Your username, in case you've forgotten: {{ user.username }}

<!-- Thank the user for using the site -->
Thanks for using our site!

<!-- Sign off from the {{ site_name }} team -->
The {{ site_name }} team.

{% endautoescape %}

users/templates/profile.html
{% extends "weather/base.html" %}
{% load static %} <!-- Loads static -->
{% load crispy_forms_tags %} 
{% block content %}
<div class="content-section text-center mt-5"> <!-- Adds text-center class for center alignment of content section -->
    <div class="media">
        {% if 'placeholder' in profile.image.url %}
            <img class="rounded-circle img-fluid account_img border border-dark border-2 rounded-4 mb-3" 
                 src="{% static 'images/default.jpg' %}" alt="">
        {% else %}
            <img class="rounded-circle img-fluid account_img border border-dark border-2 rounded-4 offset-lg-0 mb-3"
                 src="{{profile.image.url}}" alt="">
        {% endif %}
        <!--<img class="rounded-circle account-img" src="{{ user.profile.image.url }}">-->
        <div class="media-body">
            <p class="account-info text-white mb-3" style="font-size: 2em;">Username: <span class="text-black">{{ user.username }}</span></p> <!-- Add text-black class for black color -->
            <p class="account-info text-white mb-4" style="font-size: 2em;">Email: <span class="text-black">{{ user.email }}</span></p> <!-- Add text-black class for black color -->
        </div>        
    </div>
    <div> <!-- Buttons to edit or delete profile -->
        <a href="{% url 'users:edit_account' %}" class="btn btn-dark-blue btn-lg">Edit Profile</a>
        <a href="{% url 'users:delete_account' %}" class="btn btn-danger btn-lg">Delete Profile</a>
    </div>
</div>
{% endblock content %}

users/templates/profile_form.html
{% extends "weather/base.html" %}
{% block content %}

<!-- Container for the edit profile form -->
<main class="container mt-0 mb-5">

    <div class="row justify-content-center g-0 mt-5">
        <!-- Card for the edit profile form -->
        <div class="col-12 col-md-6 col-lg-5 col-xl-4 p-2 mt-5 card-welcome border border-dark border-2 rounded-4 justify-content-center">
            <!-- Form for editing profile details -->
            <form method="POST" action="{% url 'users:edit_account' %}" enctype="multipart/form-data">
                <!-- Button to navigate back to the profile -->
                <a href="{% url 'users:profile' request.user.profile.id %}" class="btn btn-secondary">Back</a>
                <!-- Heading for the edit profile section -->
                <h1 class="mb-3 mt-0">Edit Details</h1>
                <!-- CSRF token for form submission -->
                {% csrf_token %}

                <!-- Loop through form fields -->
                {% for field in form %}
                <!-- Label for the form field -->
                <label style="color: white;">{{field.label}}</label>
                <br>
                <!-- Render the form field -->
                {{field}}
                <br>
                {% endfor %}

                <!-- Submit button for saving changes -->
                <input class="btn btn-dark-blue" type="submit" value="Save">
            </form>
        </div>
    </div>
</main>
<br><br><br>

{% endblock content %}

users/templates/register.html
{% extends "weather/base.html" %}
{% load crispy_forms_tags %} 
{% block content %}
    <!-- Container for the registration form -->
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <!-- Content section with text white -->
                <div class="content-section text-white">
                    <!-- Form for user registration -->
                    <form method="POST">
                        <!-- CSRF token for form submission -->
                        {% csrf_token %}  
                        <fieldset class="form-group">
                            <!-- Legend for the registration form -->
                            <legend class="border-bottom mb-4">Register</legend>
                            <!-- Render the crispy form -->
                            {% crispy form %}
                        </fieldset>
                        <!-- Section for already registered users to sign in -->
                        <div class="border-top pt-3 text-center">
                            <small class="text-muted fs-6"> 
                                Already Have An Account? <!-- Link to sign in page -->
                                <a class="ml-2 text-black" href="{% url 'users:login' %}">Sign In</a>
                            </small>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br><br><br>
{% endblock content %}