users/urls.py
from django.urls import path, include
from . import views
from django.conf import settings  
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import url_reset

# Set the application namespace
app_name = 'users'

# Define URL patterns
urlpatterns = [
    # User registration
    path('register/', views.register, name='register'),
    
    # User login
    path('login/', views.login, name='login'),
    
    # User logout
    path('logout/', views.logout_view, name='logout'),
    
    # User profile
    path('profile/<int:pk>/', views.profile, name='profile'),
    
    # Edit user account
    path('edit_account/', views.edit_account, name='edit_account'),
    
    # Delete user account
    path('delete_account/', views.delete_account, name='delete_account'),
    
    # Password reset
    path('password-reset/', include('users.url_reset')),
]   

weather/urls.py
from django.urls import path  # Importing necessary modules
from . import views  # Importing views from the same directory

app_name = 'weather'  # Declaring the app namespace

urlpatterns = [
    path('', views.index, name='index'),  # URL pattern for the index page
    path('current/', views.current, name='current'),  # URL pattern for the current weather page
    path('hourly/', views.hourly, name='hourly'),  # URL pattern for the hourly forecast page
    path('favourites/', views.favourites, name='favourites'),  # URL pattern for the favourites page
    path('add_to_favorites/<str:city_name>/', views.add_to_favorites, name='add_to_favorites'),  # URL pattern for adding a city to favourites
    path('remove_from_favorites/<str:city_name>/', views.remove_from_favorites, name='remove_from_favorites'),  # URL pattern for removing a city from favourites
    path('hourly/<str:city_name>/', views.hourlyFcastCity, name="hourlyFcastCity")  # URL pattern for the hourly forecast of a specific city
]

weather_you_do/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import handler403, handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
    path('users/', include ('users.urls')),
]

handler403 = handler403
handler404 = handler404
handler500 = handler500

weather/models.py
from django.db import models  # Importing necessary modules
from users.models import Profile  # Importing the Profile model from the users app
from decimal import Decimal  # Importing Decimal for handling decimal numbers

class Favourite(models.Model):  # Defines a model for storing favorite cities
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE)  # Relationship with the user's profile
    city_name = models.CharField(max_length=254, null=False, blank=False)  # Name of the favorite city
    created_at = models.DateTimeField(auto_now_add=True)  # Timestamp for creation
    updated_at = models.DateTimeField(auto_now=True)  # Timestamp for last update

    class Meta:
        # Ensures that a user can only add a favorite city once
        unique_together = ('owner', 'city_name')

    def save(self, *args, **kwargs):  # Overrides save method to ensure uniformity in city names
        self.city_name = self.city_name.lower()  # Converts city name to lowercase
        return super(Favourite, self).save(*args, **kwargs)  # Calls the parent class's save method

    def __str__(self):  # Defines a string representation for the model
        # String representation showing the user and the favorite city_name
        return f"{self.owner.username}'s favorite {self.city_name}"


class HourlyForecast(models.Model):  # Defines a model for storing hourly forecasts
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE)  # Relationship with the user's profile
    city_name = models.CharField(max_length=254, null=False, blank=False)  # Name of the city
    fcast_date = models.DateField()  # Forecast date
    avg = models.DecimalField(max_digits=5, decimal_places=2, default=Decimal("0.00"))  # Average temperature
    hours_count = models.PositiveSmallIntegerField(default=0)  # Number of forecast hours

    class Meta:
        # Ensures that a user can only add a forecast for a city on a specific date once
        unique_together = ('owner', 'city_name', 'fcast_date')

    def save(self, *args, **kwargs):  # Overrides save method to ensure uniformity in city names
        self.city_name = self.city_name.lower()  # Converts city name to lowercase
        return super(HourlyForecast, self).save(*args, **kwargs)  # Calls the parent class's save method

    def __str__(self):  # Define a string representation for the model
        # String representation showing the user, city_name, and forecast date
        return f"{self.owner.username} - {self.city_name} - {self.fcast_date.strftime('%m/%d/%Y')}"

weather/forms.py
from django import forms  # Importing necessary modules

class HourlyFcastForm(forms.Form):  # Defines a form class for handling hourly forecast data
    city_name = forms.CharField(max_length=254, required=False)  # Defines a form field for city name input

    def clean_city_name(self):  # Defines a method to clean and validate city name input
        city_name = self.cleaned_data.get('city_name')  # Gets the cleaned city name input
        if not city_name:  # Checks if city name is empty
            raise forms.ValidationError('This field is required')  # Raises a validation error if city name is empty
        return city_name  # Returns the cleaned city name input

weather/views.py
# Standard Library Imports
import datetime as dt
import os
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages
from django.utils.text import capfirst
from .models import Favourite, HourlyForecast
from itertools import groupby
from operator import itemgetter
from .forms import HourlyFcastForm

# Third-Party Imports
import pytz
from dotenv import load_dotenv
import urllib.request
import urllib.parse
import json

# Django Imports
from django.shortcuts import render
from django.contrib import messages

# Country codes and names
COUNTRY_CODES = {
    "AF": "Afghanistan",
    "AL": "Albania",
    "DZ": "Algeria",	
    "AS": "American Samoa",	
    "AD": "Andorra",	
    "AO": "Angola",	
    "AI": "Anguilla",	
    "AQ": "Antarctica",	
    "AG": "Antigua and Barbuda",	
    "AR": "Argentina",	
    "AM": "Armenia",	
    "AW": "Aruba",	
    "AU": "Australia",	
    "AT": "Austria",	
    "AZ": "Azerbaijan",	
    "BS": "Bahamas (the)",	
    "BH": "Bahrain",	
    "BD": "Bangladesh",	
    "BB": "Barbados",	
    "BY": "Belarus",	
    "BE": "Belgium",	
    "BZ": "Belize",	
    "BJ": "Benin",	
    "BM": "Bermuda",	
    "BT": "Bhutan",	
    "BO": "Bolivia (Plurinational State of)",	
    "BQ": "Bonaire, Sint Eustatius and Saba",	
    "BA": "Bosnia and Herzegovina",	
    "BW": "Botswana",	
    "BV": "Bouvet Island",	
    "BR": "Brazil",	
    "IO": "British Indian Ocean Territory (the)",	
    "BN": "Brunei Darussalam",	
    "BG": "Bulgaria",	
    "BF": "Burkina Faso",	
    "BI": "Burundi",	
    "CV": "Cabo Verde",	
    "KH": "Cambodia",	
    "CM": "Cameroon",	
    "CA": "Canada",	
    "KY": "Cayman Islands (the)",	
    "CF": "Central African Republic (the)",	
    "TD": "Chad",	
    "CL": "Chile",	
    "CN": "China",	
    "CX": "Christmas Island",	
    "CC": "Cocos (Keeling) Islands (the)",	
    "CO": "Colombia",	
    "KM": "Comoros (the)",	
    "CD": "Congo (the Democratic Republic of the)",	
    "CG": "Congo (the)",	
    "CK": "Cook Islands (the)",	
    "CR": "Costa Rica",	
    "HR": "Croatia",	
    "CU": "Cuba",	
    "CW": "Curaçao",	
    "CY": "Cyprus",	
    "CZ": "Czechia",	
    "CI": "Côte d'Ivoire",	
    "DK": "Denmark",	
    "DJ": "Djibouti",	
    "DM": "Dominica",	
    "DO": "Dominican Republic (the)",	
    "EC": "Ecuador",	
    "EG": "Egypt",	
    "SV": "El Salvador",	
    "GQ": "Equatorial Guinea",	
    "ER": "Eritrea",	
    "EE": "Estonia",	
    "SZ": "Eswatini",	
    "ET": "Ethiopia",	
    "FK": "Falkland Islands (the) [Malvinas]",	
    "FO": "Faroe Islands (the)",	
    "FJ": "Fiji",	
    "FI": "Finland",	
    "FR": "France",	
    "GF": "French Guiana",	
    "PF": "French Polynesia",	
    "TF": "French Southern Territories (the)",	
    "GA": "Gabon",	
    "GM": "Gambia (the)",	
    "GE": "Georgia",	
    "DE": "Germany",	
    "GH": "Ghana",	
    "GI": "Gibraltar",	
    "GR": "Greece",	
    "GL": "Greenland",	
    "GD": "Grenada",	
    "GP": "Guadeloupe",
    "GU": "Guam",	
    "GT": "Guatemala",	
    "GG": "Guernsey",	
    "GN": "Guinea",	
    "GW": "Guinea-Bissau",	
    "GY": "Guyana",	
    "HT": "Haiti",	
    "HM": "Heard Island and McDonald Islands",	
    "VA": "Holy See (the)",	
    "HN": "Honduras",	
    "HK": "Hong Kong",	
    "HU": "Hungary",	
    "IS": "Iceland",	
    "IN": "India",	
    "ID": "Indonesia",	
    "IR": "Iran (Islamic Republic of)",	
    "IQ": "Iraq",	
    "IE": "Ireland",	
    "IM": "Isle of Man",	
    "IL": "Israel",	
    "IT": "Italy",	
    "JM": "Jamaica",	
    "JP": "Japan",	
    "JE": "Jersey",	
    "JO": "Jordan",	
    "KZ": "Kazakhstan",	
    "KE": "Kenya",	
    "KI": "Kiribati",	
    "KP": "Korea (the Democratic People's Republic of)",	
    "KR": "Korea (the Republic of)",	
    "KW": "Kuwait",	
    "KG": "Kyrgyzstan",	
    "LA": "Lao People's Democratic Republic (the)",	
    "LV": "Latvia",	
    "LB": "Lebanon",	
    "LS": "Lesotho",	
    "LR": "Liberia",	
    "LY": "Libya",	
    "LI": "Liechtenstein",	
    "LT": "Lithuania",	
    "LU": "Luxembourg",	
    "MO": "Macao",	
    "MG": "Madagascar",	
    "MW": "Malawi",	
    "MY": "Malaysia",	
    "MV": "Maldives",
    "ML": "Mali",	
    "MT": "Malta",	
    "MH": "Marshall Islands (the)",
    "MQ": "Martinique",	
    "MR": "Mauritania",	
    "MU": "Mauritiu",	
    "YT": "Mayotte",	
    "MX": "Mexico",	
    "FM": "Micronesia (Federated States of)",	
    "MD": "Moldova (the Republic of)",	
    "MC": "Monaco",	
    "MN": "Mongolia",	
    "ME": "Montenegro",	
    "MS": "Montserrat",	
    "MA": "Morocco",	
    "MZ": "Mozambique",	
    "MM": "Myanmar",	
    "NA": "Namibia",	
    "NR": "Nauru",	
    "NP": "Nepal",	
    "NL": "Netherlands (the)",	
    "NC": "New Caledonia",	
    "NZ": "New Zealand",	
    "NI": "Nicaragua",	
    "NE": "Niger (the)",	
    "NG": "Nigeria",
    "NU": "Niue",	
    "NF": "Norfolk Island",	
    "MP": "Northern Mariana Islands (the)",	
    "NO": "Norway",	
    "OM": "Oman",	
    "PK": "Pakistan",	
    "PW": "Palau",	
    "PS": "Palestine, State of",	
    "PA": "Panama",	
    "PG": "Papua New Guinea",	
    "PY": "Paraguay",	
    "PE": "Peru",	
    "PH": "Philippines (the)",	
    "PN": "Pitcairn",	
    "PL": "Poland",	
    "PT": "Portugal",	
    "PR": "Puerto Rico",	
    "QA": "Qatar",	
    "MK": "Republic of North Macedonia",		
    "RO": "Romania",	
    "RU": "Russian Federation (the)",	
    "RW": "Rwanda",	
    "RE": "Réunion",	
    "BL": "Saint Barthélemy",	
    "SH": "Saint Helena, Ascension and Tristan da Cunha",	
    "KN": "Saint Kitts and Nevis",	
    "LC": "Saint Lucia",	
    "MF": "Saint Martin (French part)",	
    "PM": "Saint Pierre and Miquelon",	
    "VC": "Saint Vincent and the Grenadines",	
    "WS": "Samoa",	
    "SM": "San Marino",	
    "ST": "Sao Tome and Principe",	
    "SA": "Saudi Arabia",	
    "SN": "Senegal",	
    "RS": "Serbia",	
    "SC": "Seychelles",	
    "SL": "Sierra Leone",	
    "SG": "Singapore",	
    "SX": "Sint Maarten (Dutch part)",	
    "SK": "Slovakia",	
    "SI": "Slovenia",	
    "SB": "Solomon Islands",	
    "SO": "Somalia",	
    "ZA": "South Africa",	
    "GS": "South Georgia and the South Sandwich Islands",	
    "SS": "South Sudan",	
    "ES": "Spain",	
    "LK": "Sri Lanka",	
    "SD": "Sudan (the)",	
    "SR": "Suriname",	
    "SJ": "Svalbard and Jan Mayen",	
    "SE": "Sweden",	
    "CH": "Switzerland",	
    "SY": "Syrian Arab Republic",	
    "TW": "Taiwan (Province of China)",	
    "TJ": "Tajikistan",	
    "TZ": "Tanzania, United Republic of",	
    "TH": "Thailand",	
    "TL": "Timor-Leste",	
    "TG": "Togo",	
    "TK": "Tokelau",
    "TO": "Tonga",	
    "TT": "Trinidad and Tobago",	
    "TN": "Tunisia",	
    "TR": "Turkey",	
    "TM": "Turkmenistan",	
    "TC": "Turks and Caicos Islands (the)",	
    "TV": "Tuvalu",	
    "UG": "Uganda",	
    "UA": "Ukraine",	
    "AE": "United Arab Emirates (the)",	
    "GB": "United Kingdom of Great Britain and Northern Ireland (the)",	
    "UM": "United States Minor Outlying Islands (the)",	
    "US": "United States of America (the)",	
    "UY": "Uruguay",	
    "UZ": "Uzbekistan",	
    "VU": "Vanuatu",	
    "VE": "Venezuela (Bolivarian Republic of)",	
    "VN": "Viet Nam",
    "VG": "Virgin Islands (British)",	
    "VI": "Virgin Islands (U.S.)",	
    "WF": "Wallis and Futuna",	
    "EH": "Western Sahara",	
    "YE": "Yemen",	
    "ZM": "Zambia",	
    "ZW": "Zimbabwe",	
    "AX": "Åland Islands",
}

# Gets the date based on the timezone
def get_date(timezone):
    tz = dt.timezone(dt.timedelta(seconds=int(timezone)))
    return dt.datetime.now(tz = tz).strftime("%Y-%m-%d, %H:%M:%S")

def index(request):
    # Renders the index.html template
    return render(request, 'weather/index.html')


# Adds city to favourites list
@login_required
def add_to_favorites(request, city_name):
    """ Add a city to the user's favorites """
    # Capitalize the city name
    city_name = capfirst(city_name)
    
    fav, created = Favourite.objects.get_or_create(
        owner=request.user.profile, city_name=city_name.lower())
    if created:
        messages.success(
            request, f'"{city_name}" has been added to your favorites!')
    else:
        messages.info(
            request, f'"{city_name}" is already in your favorites.')
    return redirect('weather:index')

# Removes city from favourites list
@login_required
def remove_from_favorites(request, city_name):
    """ Remove a city from the user's favorites """
    # Capitalize the city name
    city_name = capfirst(city_name)

    deleted, _ = Favourite.objects.filter(
        owner=request.user.profile, city_name=city_name.lower()).delete()

    if deleted:
        messages.success(
            request, f'"{city_name}" has been removed from your favorites.')
    else:
        messages.info(
            request, f'"{city_name}" was not found in your favorites.')
    return redirect('weather:index')


# Renders favourites list
@login_required
def favourites(request):
    if request.user.is_authenticated:
        # Get the list of favorite product IDs for the logged-in user
        favorite_cities = Favourite.objects.filter(
            owner=request.user.profile).values_list('city_name', flat=True)
    else:
        favorite_cities = []
    return render(request, 'weather/favourites.html', {'favorite_cities':favorite_cities})

# Fetches the current forecast data
@login_required
def current(request):
    if request.method == 'GET':
        # Gets the city name and country code from the request
        city_name = request.GET.get('city_name')
        country_code = request.GET.get('country_code')
        is_favorite = False  # Initialize is_favorite

        if city_name:
            # API key for OpenWeatherMap
            api_key = os.getenv('api_key')

            # Encodes the city name before constructing the URL
            encoded_city_name = urllib.parse.quote(city_name)

            # Constructs the URL to fetch current weather data

weather/templates/weather/base.html
{% load static %} <!-- Loads the static template tag to use static files -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content=""> <!-- Meta description -->

    <title>Weather You Do</title> <!-- Set the title of the page -->

    <!-- Links Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Links custom stylesheet -->
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">

    <!-- Inline CSS to set background image -->
    <style>
        body {
            background-image: url("{% static 'images/background.jpg' %}");
        }
    </style>

    <!-- Links Font Awesome for icons -->
    <script src="https://kit.fontawesome.com/59cd1df525.js" crossorigin="anonymous"></script>
</head>
<body class="bg-dark-subtle"> <!-- Sets body background color -->

    <!-- Navbar -->
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <!-- Navbar brand -->
            <a class="navbar-brand" href="{% url 'weather:index' %}">
                WeatherYouDo
                <!-- Logo image -->
                <img src="{% static 'images/weatheryoudo_logo.png' %}" alt="WeatherYouDo Logo" class="ms-auto">
            </a>

            <!-- Navbar links -->
            <div class="d-flex">
                <!-- Profile link or Register/Login buttons based on user authentication -->
                {% if request.user.is_authenticated %}
                    <a href="{% url 'users:profile' request.user.id %}" class="nav-link btn btn-outline-primary me-3 text-white">Profile</a>
                    <form action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="nav-link btn btn-outline-primary text-white">Logout</button>
                    </form>
                {% else %}
                    <a href="{% url 'users:register' %}" class="nav-link btn btn-outline-primary me-3 text-white">Register</a>
                    <a href="{% url 'users:login' %}" class="nav-link btn btn-outline-primary text-white">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>

    <!-- Messages container -->
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-8 offset-md-2 message-color text-center">
                <!-- Displays messages using Bootstrap alert component -->
                {% for message in messages %}
                    <div class="alert {% if message.tags == 'success' %}alert-success{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                        <span class="fs-5">
                            {{ message | safe }}
                        </span>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>    

    <!-- Main content -->
    <main class="container mb-4">
        {% block content %} <!-- Content block to be filled by child templates -->
        {% endblock %}
    </main>

    <!-- Footer -->
    <footer class="text-center text-gray p-1 fs-5 bg-dark fixed-bottom">
        <!-- Copyright notice -->
        <h1 class="fs-6 font-weight-bolder text-white">Copyright (C) 2023<br>Weather You Do</h1>
    </footer>

    <!-- Bootstrap and custom JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

weather/templates/weather/favourites.html
{% extends "weather/base.html" %} <!-- Extends base.html template -->

{% block content %} <!-- Defines content block -->

<div class="container mt-4"> <!-- Main content container -->
    <h1 class="display-6 text-center mb-5 welcome-text p-3 bg-white border rounded text-black d-inline-block font-weight-bold">Your Favourite Cities</h1> <!-- Heading for favourite cities -->

    <div class="row">
        {% for city in favorite_cities %} <!-- Loops through each favourite city -->
        <div class="col-md-4">
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ city|capfirst }}</h5> <!-- Displays city name with first letter capitalized -->
                    <p class="card-text">Check the weather for {{ city|capfirst }}.</p>
                    <!-- Buttons to view weather forecasts for the city -->
                    <a href="{% url 'weather:current' %}?city_name={{ city }}" class="btn btn-primary">Current Forecast</a>
                    <a href="{% url 'weather:hourly' %}?city_name={{ city }}" class="btn btn-primary">Hourly Forecast</a>
                    <a href="{% url 'weather:hourlyFcastCity' city_name=city %}" class="btn btn-primary mt-2">AVG Hourly Forecast</a>
                </div>
            </div>
        </div>
        {% empty %}
        <!-- Displays message if no favourite cities are added -->
        <div class="col">
            <div class="alert alert-info" role="alert">
                No favorite cities added yet.
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %} <!-- End of content block -->

weather/templates/weather/hourlyFcast.html
{% extends "weather/base.html" %} <!-- Extends base.html template -->

{% block content %} <!-- Defines content block -->

<div class="container mt-4"> <!-- Main content container -->
    <div class="row justify-content-center"> <!-- Row for centering content -->
        <div class="col-lg-10"> <!-- Column with width adjustment for large screens -->
            <div class="table-responsive"> <!-- Responsive table -->
                <table class="table table-striped table-bordered table-hover text-center"> <!-- Table styling -->
                    <thead class="thead-dark"> <!-- Table header styling -->
                        <tr>
                            <th scope="col">City</th> <!-- Table column headers -->
                            <th scope="col">Forecast Date</th>
                            <th scope="col">Average</th>
                            <th scope="col">Hours Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for f in fcast %} <!-- Loops through hourly forecast data -->
                        <tr>
                            <td>{{ f.city_name|title }}</td> <!-- Displays city name with first letter capitalized -->
                            <td>{{ f.fcast_date|date:"d/m/Y" }}</td> <!-- Displays forecast date with specified format -->
                            <td>{{ f.avg }}</td> <!-- Displays average value -->
                            <td>{{ f.hours_count }}</td> <!-- Displays hours count -->
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="4" class="text-center">No data available</td> <!-- Displays message if no data available -->
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="text-center mt-3"> <!-- Center-aligned back button -->
                <a href="{% url 'weather:favourites' %}" class="btn btn-dark-blue">Back to Favourites</a> <!-- Button to navigate back to favourites -->
            </div>            
        </div>
    </div>
</div>

{% endblock %} <!-- End of content block -->

weather/templates/weather/index.html
{% extends "weather/base.html" %} <!-- Extends base.html template -->

{% block content %} <!-- Defines content block -->

<div class="container mt-4"> <!-- Main content container -->
    <h1 class="display-6 text-center mb-5 welcome-text">{% if request.user.is_authenticated %}<span class="username">Hi {{ request.user.username }}!</span><br> Welcome to Weather You Do{% endif %}</h1> <!-- Greeting message, conditional based on user authentication -->

    {% if request.user.is_authenticated %}
        <!-- Displays cards for authenticated users -->
        <div class="row g-4">
            <!-- Profile card -->
            <div class="col-md-6">
                <div class="card h-100 mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Profile</h5>
                        <p class="card-text">Check out your profile, add/update your profile picture, username, or password.</p>
                        <a href="{% url 'users:profile' request.user.id %}" class="btn btn-primary">Go to Profile</a>
                    </div>
                </div>
            </div>
            <!-- Logout card -->
            <div class="col-md-6">
                <div class="card h-100 mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Logout</h5>
                        <p class="card-text">You can log out from here. Don't forget to tell your friends about us!</p>
                        <form action="{% url 'users:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Logout</button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- Favourites card -->
            <div class="col-md-6">
                <div class="card h-100 mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Favourites</h5>
                        <p class="card-text">View your saved favourite cities and use them to check the current and hourly forecasts.</p>
                        <a href="{% url 'weather:favourites' %}" class="btn btn-primary">View Favourites</a>
                    </div>
                </div>
            </div>
            <!-- Current Forecast card -->
            <div class="col-md-6">
                <div class="card h-100">
                    <div class="card-body mb-3">
                        <h5 class="card-title">Current Forecast</h5>
                        <p class="card-text">Find the current forecast for any city worldwide. A city name is required to search - broaden your search using the country name if necessary.</p>
                        <a href="{% url 'weather:current' %}" class="btn btn-primary">Check Current Forecast</a>
                    </div>
                </div>
            </div>
            <!-- Hourly Forecast card -->
            <div class="col-md-6">
                <div class="card h-100 mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Hourly Forecast</h5>
                        <p class="card-text">Find the hourly forecast or Average Temperature for any city worldwide for the next 4 days. A city name is required to search - broaden your search using the country name if necessary.</p>
                        <a href="{% url 'weather:hourly' %}" class="btn btn-primary">Check Hourly Forecast</a>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <!-- Displays cards for non-authenticated users -->
        <div class="row g-4">
            <!-- Register card -->
            <div class="col-md-6">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">Register</h5>
                        <p class="card-text">Have you signed up with us yet? Please do so here!</p>
                        <a href="{% url 'users:register' %}" class="btn btn-primary">Register</a>
                    </div>
                </div>
            </div>
            <!-- Login card -->
            <div class="col-md-6">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">Login</h5>
                        <p class="card-text">Already have an account? Log in here!</p>
                        <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
</div> <!-- End of main content container -->

<br><br><br> 

{% endblock content %} <!-- End of content block -->